### ISSUE TITLE
Arduino Nano Every Timer Controller

### ISSUE THREAD

**Issue by mohdrais** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#1]
I just want to know whether you are planning to make EveryTimerA. Thank you.

**Comment by Kees-van-der-Oord** [comment]
Dear Mohdrais,

The TimerA is used by the Arduino core for millis() and micros().
I'm not sure if you can use TimerA features without breaking these functions.
What would you like to use TimerA for that cannot be done with TimerB0, 1 and 2 ?

WR,

Kees

**Comment by Kees-van-der-Oord** [comment]
Mohdrais,

I gave some suggestions on:
https://forum.arduino.cc/index.php?topic=626736.new

WR,

Kees

**Comment by Kees-van-der-Oord** [comment]
Dear Mohdrais,

I added the method:
void setPwmMode(byte period, byte compare)

You can use this for TCB0 to enable PWM on pin 6 and for TCB1 to enable PWM on pin 3.

The period argument (1-255) determines together with the clock the frequency:
	//  16MHz clock: slowest frequency @ 255 = 62 kHz.
	//   8MHz clock: slowest frequency @ 255 = 31 kHz.
	// 256kHz clock: slowest frequency @ 255 =  1 kHz.
If you select a lower period than 255, the frequency will be faster.
The compare argument should be lower than the period argument and determines the duty cycle. If the compare argument is 2x smaller than the period, the duty cycle is 50 %.

EveryTimerB   TimerB0;
TimerB0.initialize(&TCB0);
TimerB0.setClockSource(TCB_CLKSEL_CLKTCA_gc); // 250 kHz clock
pinMode(6,OUTPUT);
TimerB0.setPwmMode(127,64); // 2 kHz frequency, 50% duty cycle

I hope this helps.

Kees

**Comment by mohdrais** [comment]
TQVM for your help. Everything you posted is a BIG help
