### ISSUE TITLE
Calling Timer1.setPeriod() in main loop breaks sketch

### ISSUE THREAD

**Issue by hxlnt** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#10]
The original TimerOne library allows calling Timer1.setPeriod() in the main loop to allow for rapid changing of the interrupt interval (i.e., changing with an encoder). However, this does not appear to work in this library. 

Here's a basic repro that blinks the on-board LED at a varying tempo. Calling Timer1.setPeriod() in the interrupt routine works, but not when in the main loop.

```
#include <EveryTimerB.h>
#define Timer1 TimerB2 // use TimerB2 as a drop in replacement for Timer1

const byte TEMPO_LED_PIN = LED_BUILTIN; // 13
unsigned long tempo = 120;
bool tempoLEDOn = false;

void setup() {
  pinMode(TEMPO_LED_PIN, OUTPUT);
  digitalWrite(TEMPO_LED_PIN, LOW);
  Timer1.initialize();
  Timer1.attachInterrupt(clockedRoutine);
  Timer1.setPeriod(60L * 1000000 / tempo);
}

void loop() {
  // Timer1.setPeriod(60L * 1000000 / tempo); <-- Breaks entire sketch when uncommented
}

void clockedRoutine() {
    if (tempoLEDOn) { 
      digitalWrite(TEMPO_LED_PIN, LOW); 
      tempoLEDOn = false; } 
    else { digitalWrite(TEMPO_LED_PIN, HIGH); 
      tempoLEDOn = true; }
  if (tempo < 300) { tempo++; } else { tempo = 120; }
  // Timer1.setPeriod(60L * 1000000 / tempo); <--- Works when uncommented
}
``` 

Environment: Arduino Nano Every board, Arduino IDE 2.3.2, Mac OS 14.3

**Comment by Kees-van-der-Oord** [comment]
dear hxInt,

In your sketch example, the loop() function continuously restarts the timer, which as a result will never overflow.

I think the sketch below implements what you would like to achieve:
- when the timer interrupt function changes the tempo, it sets the volatile flag 'tempoChanged'
- when the main loop detects that this flag is set, the timer is reprogrammed (and clears the flag).

The variable 'tempoChanged' must be declared as volatile to tell the compiler that it will be changed by another thread (the interrupt routine). 

I hope this helps you with your challenges !

WR,

Kees 

```
#include "EveryTimerB.h"
#define Timer1 TimerB2

const byte TEMPO_LED_PIN = LED_BUILTIN; // 13
volatile unsigned long tempo = 120;
volatile bool tempoChanged = false;
bool tempoLEDOn = false;

void setup() {
  pinMode(TEMPO_LED_PIN, OUTPUT);
  digitalWrite(TEMPO_LED_PIN, LOW);
  Timer1.initialize();
  Timer1.attachInterrupt(clockedRoutine);
  Timer1.setPeriod(60L * 1000000 / tempo);
}

void loop() {
  if(tempoChanged) {
    tempoChanged = false;
    Timer1.setPeriod(60L * 1000000 / tempo);
  }
}

void clockedRoutine() {
    if (tempoLEDOn) { 
      digitalWrite(TEMPO_LED_PIN, LOW); 
      tempoLEDOn = false; } 
    else { digitalWrite(TEMPO_LED_PIN, HIGH); 
      tempoLEDOn = true; }
  if (tempo < 300) { tempo++; } else { tempo = 120; }
  tempoChanged = true;
  // Timer1.setPeriod(60L * 1000000 / tempo); // <--- Works when uncommented
}
```
