### ISSUE TITLE
variable frequency PWM

### ISSUE THREAD

**Issue by mohdrais** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#2]
Dear Sir, can your library be used to varies PWM frequency, by using variable potentiometer. TQVM

**Comment by Kees-van-der-Oord** [comment]
Dear Modrais,

the Arduino core supports this already.

on this page you find the information on which pins support PWM:
D3, D5, D6, D9, D10 and D11.
https://forum.arduino.cc/index.php?topic=644395.0

The PWM mode is enabled by using analogWrite:
analogWrite(6,128);
will set the PWM to a 50% duty cycle.

WR,

Kees

**Comment by mohdrais** [comment]
Dear Kees-van-der-Oord,
How to change the PWM frequency? Tried to read the datasheet, but it is too complex (for me)! TQVM

**Comment by Kees-van-der-Oord** [comment]
Dear Mohdrais,

I added the PWM functions to the example sketch example/EveryTimerBExample.ino,
and tested them with a LED. The LED intensity changes as expected, so I guess that
the PWM working OK.
If you get the latest version of all files and upload the example sketch, you can explore
the PWM with the following commands:
t     this will select the next timer TCB0 (on startup TCB2 is selected)
p    this will toggle to the pwm mode (TCB0: pin 6, TCB1: pin 3)
c     this will cycle through the clock sources.
\+    this will make the PWM faster (period / 2)
\-     this will make the PWM slower (period * 2)
u    this will make the duty cycle larger
d    this will make the duty cycle smaller

Make sure that both pin 3 and 6 are not tight to ground or another output.

Have fun,

Kees

**Comment by mohdrais** [comment]
TQVM for your kind help
