### ISSUE TITLE
Invalid library error when trying to add

### ISSUE THREAD

**Issue by w8be** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#3]
Tying to install the zip version of the library for the Nano Every.   I am getting this error:
Specified folder/zip file does not contain a valid library

I also extracted the library and install it manually.    The IDE does not see the library in the include directory and throws and invalid library error when I compile a sketch.   

I am not very versed in programming so any comments appreciated.

**Comment by Kees-van-der-Oord** [comment]
Dear w8be,

I'm about on the same level as you :-)
Please unpack the two .h and the .cpp file to your sketch folder.
Now the compiler should be able to find them.

note that in this thread an alternative solution is proposed to to fix the incorrect millis() and micros() at 20 MHz: 
[https://github.com/arduino-libraries/Servo/issues/29#issuecomment-661987476](https://github.com/arduino-libraries/Servo/issues/29#issuecomment-661987476)
these changes in the timer.h header file fix the problem less accurate, but much more efficient. 

WR,
Kees
