### ISSUE TITLE
invalid conversion from 'int' to 'TCB_CLKSEL_t

### ISSUE THREAD

**Issue by idekkers** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#4]
Hi

trying to verify the code, I get a lot of errors regarding conversions and "large integer implicitly truncated to unsigned type"

using Arduino 1.8.13 

I have a new project file that only has the includes from your sample and I get this: 

`
In file included from D:\users\XXX\Documents\Arduino\sketch_oct07a\sketch_oct07a.ino:3:0:
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h: In member function 'TCB_CLKSEL_t EveryTimerB::getClockSource()':
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:88:25: warning: invalid conversion from 'int' to 'TCB_CLKSEL_t {aka TCB_CLKSEL_enum}' [-fpermissive]
     return timer->CTRLA & (TCB_CLKSEL_CLKTCA_gc | TCB_CLKSEL_CLKDIV2_gc | TCB_CLKSEL_CLKDIV1_gc);
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:\users\XXX\Documents\Arduino\sketch_oct07a\sketch_oct07a.ino:3:0:
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h: In member function 'void EveryTimerB::setPeriod(long unsigned int)':
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:25:24: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define TCB_RESOLUTION 65536UL // TCB is 16 bit
                        ^
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:151:25: note: in expansion of macro 'TCB_RESOLUTION'
     countsPerOverflow = TCB_RESOLUTION;
                         ^~~~~~~~~~~~~~
In file included from D:\users\XXX\Documents\Arduino\sketch_oct07a\sketch_oct07a.ino:3:0:
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h: In member function 'TCB_CNTMODE_enum EveryTimerB::getMode()':
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:242:25: warning: invalid conversion from 'int' to 'TCB_CNTMODE_enum' [-fpermissive]
     return timer->CTRLB & 0x7;
            ~~~~~~~~~~~~~^~~~~
`

when adding more libraries, I get a lot more errors?
no errors appear when not importing EveryTimerB.

any idea what I'm doing  wrong?
thanks

**Comment by Kees-van-der-Oord** [comment]
Dear IDekkers,

it looks like 1.8.13 issues more warnings than the previous versions.
i added the type casting that should prevent the warnings above.
please fetch the new version of EveryTimerB.h.

as these are only warnings, I expect that your sketch is compiled ?

WR,

Kees

**Comment by idekkers** [comment]
don't get these any more, 
but I get new ones: 
`
In file included from D:\users\XXX\Documents\Arduino\sketch_oct07a\sketch_oct07a.ino:3:0:
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h: In member function 'void EveryTimerB::setPeriod(long unsigned int)':
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:89:24: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define TCB_RESOLUTION 65536UL // TCB is 16 bit
                        ^
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB/EveryTimerB.h:187:27: note: in expansion of macro 'TCB_RESOLUTION'
       countsPerOverflow = TCB_RESOLUTION;
                           ^~~~~~~~~~~~~~
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB\EveryTimerB.cpp:14:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 #endif ARDUINO_ARCH_MEGAAVR
        ^~~~~~~~~~~~~~~~~~~~
In file included from D:\users\XXX\Documents\Arduino\libraries\EveryTimerB\EveryTimerB.cpp:2:0:
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB\EveryTimerB.h: In member function 'void EveryTimerB::setPeriod(long unsigned int)':
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB\EveryTimerB.h:89:24: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define TCB_RESOLUTION 65536UL // TCB is 16 bit
                        ^
D:\users\XXX\Documents\Arduino\libraries\EveryTimerB\EveryTimerB.h:187:27: note: in expansion of macro 'TCB_RESOLUTION'
       countsPerOverflow = TCB_RESOLUTION;
                           ^~~~~~~~~~~~~~

`

also, i get errors on the "#endif" in the end of the file, 
I just added comments to the explanation text and they went away: 
`
#endif //ARDUINO_ARCH_MEGAAVR
#endif //EveryTimerB_h_
`

thanks so much for your work on this, and sorry I cannot help, just started learning arduino and CPP so I can't fix most of these....

**Comment by idekkers** [comment]
OK, got rid of all the warnings in the library itself: 
3 of them where in comments after the "#endif" as noted in the previous post, at the end of EveryTimerB.h, there is another one at the end of EveryTimerB.cpp
the last one above was a definition of "#define TCB_RESOLUTION 65536U" at line 89, but then assigning it to a short at line 380 : 
"unsigned long countsPerOverflow = (unsigned long) (TCB_RESOLUTION - 1);"
I changed unsigned short to long, though I don't know if it's the correct fix?

now there is just the issue of warning when using with other libraries: 
RTClib
Adafruit_BME280
Adafruit_CCS811

all give warnings when used with EveryTimerB, all of them are conversion issues : 
"warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second"

the file I use is just importing these libraries, no extra code

thanks again for your work

**Comment by Kees-van-der-Oord** [comment]
Dear iDekkers,

It is weird that you get warnings with the code that I don't see, while we are using the same Arduino version 1.8.13.
The changes you applied are perfectly fine: the only negative side effect is that the memory usage is 2 bytes larger.
I will push these changes to the repository.

For the errors with the RTClib and Adafruit libraries: I can reproduce them even in a sketch where only the #include "RTClib.h"
library is included. They appear only once after changing the board type: the next compile the pre-compiled code is re-used. 
There are only warnings: it is difficult to judge Adafruit if the code works fine on the megaAVR boards ...

WR,

Kees

**Comment by idekkers** [comment]
thank you so much, I will test the code with the RTC and sensors and see if all works fine, and only if not, I'll post the error I get.
otherwise consider it working : )
