### ISSUE TITLE
disablePwm function on TimerOne not implemented in EveryTimerB

### ISSUE THREAD

**Issue by Asbelos** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#5]
I'm trying to get a timer interrupt without any pins changing. Unfortunately I can't understand your comment in the readme  about how to do this for EveryTimerB.

" If you don't use PWM on these pins you can define a TimerB object for TCB0 and TCB1 and copy the ISR code from the
EveryTimerB.cpp file."

 My UNO/Mega code uses the TimerOne disablePwm() like this: 

```
  Timer1.initialize(NORMAL_SIGNAL_TIME);
   // See disablePwm in TinerOne.h for possible pins to disable
  #ifdef TIMER1_A_PIN
   Timer1.disablePwm(TIMER1_A_PIN);
  #endif
  #ifdef TIMER1_B_PIN
   Timer1.disablePwm(TIMER1_B_PIN);
  #endif
  #ifdef TIMER1_C_PIN
   Timer1.disablePwm(TIMER1_C_PIN);
  #endif
   Timer1.attachInterrupt(interruptHandler);
   Timer1.start();
```
Any help would be appreciated.

**Comment by Kees-van-der-Oord** [comment]
Dear Asbelos,

The Nano Every Timers PWM functionality is disabled on startup.
You don't need to disable it.
If you want to use PWM, you have to enable it using the method setPwmMode(period,compare).

WR,

Kees

**Comment by Kees-van-der-Oord** [comment]
Once the timer is set to PWM mode, you can 'disable' it again by setting it to the timer mode (setTimerMode()).
