### ISSUE TITLE
Change Frequency

### ISSUE THREAD

**Issue by Sarah26-10** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#7]
Hello there :)
thanks for the NanoEvery Implementation.
I want to generate a PWM signal for a Servo Motor and need to change the frequency to change the motor speed.
While initialising the Timer object with other default values (default is 1s - i changed it to 30microseconds) the frequency changes like expected. But afterwards i can't change the period with setPeriod(). 

Do i have to diable the object in some way? Or is that not possible?

Greetings :)

**Comment by Kees-van-der-Oord** [comment]
Dear Sarah,

I don't think the PWM mode is most appropriate mode to control a stepper motor.
Servo movement is most smooth if the frequency starts slow and increases frequency (ramping up),
next move with a fixed frequency and finally decrease the frequency to slow down (ramping down).
http://pthat.com/index.php/motor-information/#tabs_desc_692_4

The easiest way to control a servo motor is to use a motor control shield such as:
https://store.arduino.cc/products/arduino-motor-shield-rev3

If you want to generate the pulses from an Arduino, you have to check if the digital outputs of the
board deliver enough current for the motor.
By default the NanoEvery PWM frequency seems to be 62.5 kHz. I think that is too fast for servo motors.
You can use a timer  (e.g. the Every TimerB) to generate the pulses.
The pseudo code would be something like this:

int initial_period = 1000;          // start the move with 1000 us pulses (1 kHz)
int ramp_up = 5;                        // make the period 5 us shorter when ramping up
int max_speed_period = 200; // cruising speed  has pulses of 200 us (5 kHz)
// for slowing down use the same settings:
int ramp_down = ramp_up;
int last_period = initial_period;

enum ePhase { PULLUP, CRUISE, BRAKE, ARRIVED};
ePhase  phase;
int ramping_steps;
int cruising_steps;
int current_step;
int distance;
int direction;
int current_period;
int edge;  //  0 to 3 for the stepping phases

int move(int steps)
{
    Timer1.stop();
    distance = abs(steps);
    direction = steps > 0 ? 1 : -1;
    ramping_steps = initial_period / ramp_up + last_period / ramp_down;
    if(ramping_steps > distance)
   {
      ramping_steps = distance;
      cruising_steps = 0;
   }
   else
  {
      cruising_steps = distance - ramping_steps;
  }
   ramping_steps /= 2;
   current_step = 0;
   current_period = initial_period;
   edge = 0;
   Timer1.SetPeriod(current_period);
   output_pulse();
}

timer_proc()
{
    output_pulse();
   ++current_step;
   switch(phase)
   {
      case PULLUP:
         current_period -= ramp_up;
         if(current_step > ramping_step)
         {
            phase = CRUISE;
         }
         break;
      case CRUISE:
         if(current_step > (ramping_step + cruising_steps))
         {
            phase = BRAKE;
         }
         break;
      case BREAK:
         current_period += ramp_down;
         if(current_step > distance))
         {
            phase = ARRIVED;
         }
         break;
   }
   if(phase != ARRIVED)
  {
      Timer1.SetPeriod(current_period);
  }
}

I hope this helps.

WR,

Kees
