### ISSUE TITLE
More than one timer

### ISSUE THREAD

**Issue by Frohnix** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#8]
Hi,
is it possible to add a second timer with different period?

**Comment by Kees-van-der-Oord** [comment]
The chip has three timers: B0, B1, B2.
The library initiates an instances of B2 only.
The example sketch shows how to initiate instances for the B0 and B1 timers:

// declaration:
EveryTimerB   TimerB0;
EveryTimerB   TimerB1;

// initialization:
void init() {
  TimerB0.initialize(&TCB0);
  TimerB0.stop();
  TimerB0.attachInterrupt(myisr);
  TimerB1.initialize(&TCB1);
  TimerB1.stop();
  TimerB1.attachInterrupt(myisr);
  TimerB2.initialize(&TCB2);
  TimerB2.stop();
  TimerB2.attachInterrupt(myisr);
}

// interrupt service routines: (only for B0 and B1: the ISR for B2 is in the library)

// code timer B0
ISR(TCB0_INT_vect)
{
  TimerB0.next_tick();
  TCB0.INTFLAGS = TCB_CAPT_bm; // writing to the INTFLAGS register clears the interrupt request flag
}

// code timer B1
ISR(TCB1_INT_vect)
{
  TimerB1.next_tick();
  TCB1.INTFLAGS = TCB_CAPT_bm; // writing to the INTFLAGS register clears the interrupt request flag
}
