### ISSUE TITLE
File name case incorrect

### ISSUE THREAD

**Issue by w9cf** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#9]
The code imports MegaAvr20MHz.h but the file name is MegaAvr20Mhz.h with a lower case h in Mhz. This
breaks on linux where the file system is case sensitive.

**Comment by Kees-van-der-Oord** [comment]
Dear W9cF,
As a physics teacher, I feel ashamed on making this mistake.
It has been corrected.
WR,
Kees
